// <auto-generated />
using System;
using LiberyDBDeliveryService.Models.DB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiberyDBDeliveryService.Migrations
{
    [DbContext(typeof(DeliveryServiceContext))]
    partial class DeliveryServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LiberyDBDeliveryService.Models.DB.Table.Account", b =>
                {
                    b.Property<long>("IdTelegram")
                        .HasColumnType("bigint")
                        .HasColumnName("idTelegram");

                    b.Property<short>("Post")
                        .HasColumnType("smallint")
                        .HasColumnName("post");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("Life")
                        .HasColumnType("bit")
                        .HasColumnName("life");

                    b.Property<string>("LoginTelegram")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loginTelegram")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("IdTelegram", "Post", "Name");

                    b.HasIndex(new[] { "IdTelegram" }, "KEY_Account_idTelegram")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("LiberyDBDeliveryService.Models.DB.Table.Order", b =>
                {
                    b.Property<long>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("idOrder");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdOrder"), 1L, 1);

                    b.Property<string>("AddresClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("addresClient")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("AddresWarehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("addresWarehouse")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("DateOrder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dateOrder")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("DeliveryTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("deliveryTime")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double>("Deposit")
                        .HasColumnType("float")
                        .HasColumnName("deposit");

                    b.Property<string>("Describe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("describe")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("FenceTime")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("fenceTime")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<long?>("IdTelegramDeliver")
                        .HasColumnType("bigint")
                        .HasColumnName("idTelegramDeliver");

                    b.Property<long>("IdTelegramShop")
                        .HasColumnType("bigint")
                        .HasColumnName("idTelegramShop");

                    b.Property<string>("PhoneClient")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("phoneClient")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("PhoneSenders")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phoneSenders")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<short>("StatusOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("statusOrder");

                    b.Property<string>("TypeMovement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("typeMovement")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("IdOrder")
                        .HasName("PK_Order_Id");

                    b.HasIndex("IdTelegramDeliver");

                    b.HasIndex("IdTelegramShop");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("LiberyDBDeliveryService.Models.DB.Table.WorkShift", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<long>("IdTelegramEmploye")
                        .HasColumnType("bigint")
                        .HasColumnName("idTelegramEmploye");

                    b.Property<long>("IdWorkShift")
                        .HasColumnType("bigint")
                        .HasColumnName("idWorkShift");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasIndex(new[] { "IdTelegramEmploye", "IdWorkShift" }, "IDX_WorkShift");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "IdTelegramEmploye", "IdWorkShift" }, "IDX_WorkShift"));

                    b.ToTable("WorkShift", (string)null);
                });

            modelBuilder.Entity("LiberyDBDeliveryService.Models.DB.Table.Order", b =>
                {
                    b.HasOne("LiberyDBDeliveryService.Models.DB.Table.Account", "IdTelegramDeliverNavigation")
                        .WithMany("OrderIdTelegramDeliverNavigations")
                        .HasForeignKey("IdTelegramDeliver")
                        .HasPrincipalKey("IdTelegram")
                        .HasConstraintName("FK_Order_idTelegramEmploye");

                    b.HasOne("LiberyDBDeliveryService.Models.DB.Table.Account", "IdTelegramShopNavigation")
                        .WithMany("OrderIdTelegramShopNavigations")
                        .HasForeignKey("IdTelegramShop")
                        .HasPrincipalKey("IdTelegram")
                        .IsRequired()
                        .HasConstraintName("FK_Order_idTelegramShop");

                    b.Navigation("IdTelegramDeliverNavigation");

                    b.Navigation("IdTelegramShopNavigation");
                });

            modelBuilder.Entity("LiberyDBDeliveryService.Models.DB.Table.WorkShift", b =>
                {
                    b.HasOne("LiberyDBDeliveryService.Models.DB.Table.Account", "IdTelegramEmployeNavigation")
                        .WithMany()
                        .HasForeignKey("IdTelegramEmploye")
                        .HasPrincipalKey("IdTelegram")
                        .IsRequired()
                        .HasConstraintName("FK_WorkShift_idTelegramEmploye");

                    b.Navigation("IdTelegramEmployeNavigation");
                });

            modelBuilder.Entity("LiberyDBDeliveryService.Models.DB.Table.Account", b =>
                {
                    b.Navigation("OrderIdTelegramDeliverNavigations");

                    b.Navigation("OrderIdTelegramShopNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
